"""Phase 10 — Town Generator.

Arranges building OBJs into a realistic small town layout with roads,
curbs, sidewalks, and procedural trees. Exports scene descriptor JSON
+ infrastructure OBJ meshes.

Usage:
    python generate_town.py --output ./town_export
    python generate_town.py --output ./town_export --n_buildings 40 --seed 42
"""
import os
import sys
import json
import argparse
import time
import numpy as np
from dataclasses import dataclass, field, asdict

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
MODELS_DIR = os.path.expanduser("~/Downloads/models")
CATALOG_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                             "building_catalog.json")

# Town layout
TOWN_W = 500.0       # X extent (meters)
TOWN_H = 400.0       # Y extent (meters)
MAIN_ROAD_W = 14.0   # Main road width
SIDE_ROAD_W = 8.0    # Secondary road width
CURB_H = 0.15        # Curb height
CURB_W = 0.20        # Curb width
SIDEWALK_W = 3.0     # Sidewalk width
BUILDING_SETBACK = 2.0  # Gap between sidewalk and building
TREE_SPACING = 15.0   # Trees every N meters along streets
TREE_TRUNK_R = 0.25
TREE_TRUNK_H = 3.5
TREE_CROWN_R = 2.5
TREE_CROWN_H = 4.5
TREE_SIDES = 8        # Polygon sides for tree cylinder/cone


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------
@dataclass
class BuildingInfo:
    file: str
    dims: list          # [width_x, depth_y, height_z]
    n_verts: int
    n_faces: int
    bounds_min: list
    bounds_max: list
    center: list


@dataclass
class BuildingPlacement:
    file: str
    position: list      # [x, y, z]
    rotation_deg: float
    dims: list
    footprint: list     # [x0, y0, x1, y1] axis-aligned bounding box


@dataclass
class RoadSegment:
    x0: float
    y0: float
    x1: float
    y1: float
    width: float
    is_main: bool


# ---------------------------------------------------------------------------
# Building catalog
# ---------------------------------------------------------------------------
def load_catalog(models_dir, catalog_path):
    """Load building catalog from JSON (generated by scan_buildings.py)."""
    if os.path.exists(catalog_path):
        with open(catalog_path) as f:
            data = json.load(f)
        return [BuildingInfo(**d) for d in data]
    else:
        raise FileNotFoundError(
            f"Building catalog not found: {catalog_path}\n"
            f"Run scan_buildings.py first.")


def select_buildings(catalog, n, seed=42):
    """Select N diverse buildings from catalog."""
    rng = np.random.default_rng(seed)

    # Sort by height for diversity
    by_height = sorted(catalog, key=lambda b: b.dims[2])

    # Stratified sampling: pick evenly from height distribution
    indices = np.linspace(0, len(by_height) - 1, min(n, len(by_height)),
                          dtype=int)
    # Add some randomness
    selected = [by_height[i] for i in indices]

    # If we need more, cycle through catalog with shuffling
    full_catalog = list(catalog)
    rng.shuffle(full_catalog)
    idx = 0
    while len(selected) < n:
        selected.append(full_catalog[idx % len(full_catalog)])
        idx += 1

    rng.shuffle(selected)
    return selected[:n]


# ---------------------------------------------------------------------------
# Town layout
# ---------------------------------------------------------------------------
def generate_road_grid(town_w, town_h, seed=42):
    """Generate road grid dividing town into blocks.

    Returns list of RoadSegments and list of block AABBs.
    """
    rng = np.random.default_rng(seed)

    # Generate N-S road X positions (vertical roads)
    ns_positions = []
    x = 0.0
    ns_positions.append((x, True))  # left edge, main road
    x += MAIN_ROAD_W

    while x < town_w - 30:
        block_w = rng.uniform(70, 110)
        x += block_w
        is_main = len(ns_positions) % 3 == 0
        road_w = MAIN_ROAD_W if is_main else SIDE_ROAD_W
        ns_positions.append((x, is_main))
        x += road_w

    # Right edge
    ns_positions.append((town_w - MAIN_ROAD_W, True))

    # Generate E-W road Y positions (horizontal roads)
    ew_positions = []
    y = 0.0
    ew_positions.append((y, True))  # bottom edge
    y += MAIN_ROAD_W

    while y < town_h - 30:
        block_h = rng.uniform(60, 90)
        y += block_h
        is_main = len(ew_positions) % 3 == 0
        road_w = MAIN_ROAD_W if is_main else SIDE_ROAD_W
        ew_positions.append((y, is_main))
        y += road_w

    ew_positions.append((town_h - MAIN_ROAD_W, True))

    # Create road segments
    roads = []

    # N-S roads (vertical, full height)
    for rx, is_main in ns_positions:
        w = MAIN_ROAD_W if is_main else SIDE_ROAD_W
        roads.append(RoadSegment(rx, 0, rx + w, town_h, w, is_main))

    # E-W roads (horizontal, full width)
    for ry, is_main in ew_positions:
        w = MAIN_ROAD_W if is_main else SIDE_ROAD_W
        roads.append(RoadSegment(0, ry, town_w, ry + w, w, is_main))

    # Extract blocks (spaces between roads)
    blocks = []
    # Sort road edges
    ns_edges = sorted([(rx, MAIN_ROAD_W if m else SIDE_ROAD_W)
                       for rx, m in ns_positions])
    ew_edges = sorted([(ry, MAIN_ROAD_W if m else SIDE_ROAD_W)
                       for ry, m in ew_positions])

    for i in range(len(ns_edges) - 1):
        x0 = ns_edges[i][0] + ns_edges[i][1]  # right edge of left road
        x1 = ns_edges[i + 1][0]                # left edge of right road
        if x1 - x0 < 20:
            continue
        for j in range(len(ew_edges) - 1):
            y0 = ew_edges[j][0] + ew_edges[j][1]
            y1 = ew_edges[j + 1][0]
            if y1 - y0 < 20:
                continue
            blocks.append([x0, y0, x1, y1])

    return roads, blocks


def place_buildings(blocks, buildings, seed=42):
    """Place buildings within blocks."""
    rng = np.random.default_rng(seed + 1)
    placements = []
    bi = 0  # building index

    for block in blocks:
        bx0, by0, bx1, by1 = block
        block_w = bx1 - bx0
        block_h = by1 - by0

        # Inset by sidewalk + setback
        inset = SIDEWALK_W + BUILDING_SETBACK
        inner_w = block_w - 2 * inset
        inner_h = block_h - 2 * inset

        if inner_w < 15 or inner_h < 10:
            continue

        # Try to fit buildings in a grid within the block
        placed_in_block = []
        cursor_y = by0 + inset
        max_per_block = 6
        attempts = 0

        while cursor_y < by1 - inset - 10 and len(placed_in_block) < max_per_block:
            if bi >= len(buildings):
                break

            bldg = buildings[bi % len(buildings)]
            bw, bd, bh = bldg.dims

            # Try both orientations — prefer the one that fits width
            fits_normal = (bw <= inner_w and bd + cursor_y - by0 - inset <= inner_h)
            fits_rotated = (bd <= inner_w and bw + cursor_y - by0 - inset <= inner_h)

            if not fits_normal and not fits_rotated:
                bi += 1
                attempts += 1
                if attempts > 10:
                    break
                continue

            if fits_normal and fits_rotated:
                rotate = rng.random() < 0.3
            elif fits_rotated:
                rotate = True
            else:
                rotate = False

            rot_deg = 90.0 if rotate else 0.0
            eff_w = bd if rotate else bw
            eff_d = bw if rotate else bd

            cx = bx0 + inset + inner_w / 2 + rng.uniform(-3, 3)
            cy = cursor_y + eff_d / 2

            if cy + eff_d / 2 > by1 - inset:
                bi += 1
                attempts += 1
                if attempts > 10:
                    break
                continue

            fp = [cx - eff_w / 2, cy - eff_d / 2,
                  cx + eff_w / 2, cy + eff_d / 2]

            p = BuildingPlacement(
                file=bldg.file,
                position=[cx, cy, 0.0],
                rotation_deg=rot_deg,
                dims=bldg.dims,
                footprint=fp,
            )
            placements.append(p)
            placed_in_block.append(p)
            bi += 1
            attempts = 0

            # Advance cursor
            cursor_y = cy + eff_d / 2 + 8.0  # 8m gap between buildings

    return placements


# ---------------------------------------------------------------------------
# Geometry generation (numpy-vectorized)
# ---------------------------------------------------------------------------
def make_quad(x0, y0, x1, y1, z=0.0):
    """Create a flat quad (2 triangles)."""
    verts = np.array([
        [x0, y0, z], [x1, y0, z], [x1, y1, z], [x0, y1, z]
    ], dtype=np.float32)
    faces = np.array([[0, 1, 2], [0, 2, 3]], dtype=np.int32)
    return verts, faces


def generate_road_meshes(roads):
    """Generate road surface quads (slightly above ground to avoid z-fighting)."""
    all_v, all_f = [], []
    offset = 0
    for r in roads:
        v, f = make_quad(r.x0, r.y0, r.x1, r.y1, z=0.02)
        all_v.append(v)
        all_f.append(f + offset)
        offset += len(v)
    return np.vstack(all_v), np.vstack(all_f)


def make_curb_strip(x0, y0, x1, y1, height, width, side='left'):
    """Create an extruded curb strip (box)."""
    # Determine orientation
    dx = x1 - x0
    dy = y1 - y0
    length = np.sqrt(dx * dx + dy * dy)

    if length < 0.1:
        return np.zeros((0, 3), np.float32), np.zeros((0, 3), np.int32)

    # 8 vertices: 4 bottom + 4 top
    verts = np.array([
        [x0, y0, 0], [x1, y1, 0],
        [x0 + width * (dy / length if side == 'left' else -dy / length),
         y0 + width * (-dx / length if side == 'left' else dx / length), 0],
        [x1 + width * (dy / length if side == 'left' else -dy / length),
         y1 + width * (-dx / length if side == 'left' else dx / length), 0],
        # Top
        [x0, y0, height], [x1, y1, height],
        [x0 + width * (dy / length if side == 'left' else -dy / length),
         y0 + width * (-dx / length if side == 'left' else dx / length), height],
        [x1 + width * (dy / length if side == 'left' else -dy / length),
         y1 + width * (-dx / length if side == 'left' else dx / length), height],
    ], dtype=np.float32)

    faces = np.array([
        # Bottom
        [0, 1, 3], [0, 3, 2],
        # Top
        [4, 7, 5], [4, 6, 7],
        # Sides
        [0, 4, 5], [0, 5, 1],
        [2, 3, 7], [2, 7, 6],
        [0, 2, 6], [0, 6, 4],
        [1, 5, 7], [1, 7, 3],
    ], dtype=np.int32)

    return verts, faces


def generate_curb_meshes(roads):
    """Generate curb strips along all road edges."""
    all_v, all_f = [], []
    offset = 0

    for r in roads:
        # For N-S roads (tall thin rectangles)
        if (r.y1 - r.y0) > (r.x1 - r.x0):
            # Left curb
            v, f = make_curb_strip(r.x0, r.y0, r.x0, r.y1,
                                    CURB_H, CURB_W, 'right')
            if len(v) > 0:
                all_v.append(v)
                all_f.append(f + offset)
                offset += len(v)
            # Right curb
            v, f = make_curb_strip(r.x1, r.y0, r.x1, r.y1,
                                    CURB_H, CURB_W, 'left')
            if len(v) > 0:
                all_v.append(v)
                all_f.append(f + offset)
                offset += len(v)
        else:
            # E-W roads
            # Bottom curb
            v, f = make_curb_strip(r.x0, r.y0, r.x1, r.y0,
                                    CURB_H, CURB_W, 'left')
            if len(v) > 0:
                all_v.append(v)
                all_f.append(f + offset)
                offset += len(v)
            # Top curb
            v, f = make_curb_strip(r.x0, r.y1, r.x1, r.y1,
                                    CURB_H, CURB_W, 'right')
            if len(v) > 0:
                all_v.append(v)
                all_f.append(f + offset)
                offset += len(v)

    if not all_v:
        return np.zeros((0, 3), np.float32), np.zeros((0, 3), np.int32)
    return np.vstack(all_v), np.vstack(all_f)


def generate_sidewalk_meshes(roads):
    """Generate sidewalk strips along road edges."""
    all_v, all_f = [], []
    offset = 0

    for r in roads:
        sw = SIDEWALK_W
        if (r.y1 - r.y0) > (r.x1 - r.x0):
            # N-S road — sidewalks on left and right
            # Left sidewalk
            v, f = make_quad(r.x0 - sw - CURB_W, r.y0,
                              r.x0 - CURB_W, r.y1, z=0.01)
            all_v.append(v); all_f.append(f + offset); offset += len(v)
            # Right sidewalk
            v, f = make_quad(r.x1 + CURB_W, r.y0,
                              r.x1 + CURB_W + sw, r.y1, z=0.01)
            all_v.append(v); all_f.append(f + offset); offset += len(v)
        else:
            # E-W road — sidewalks on top and bottom
            v, f = make_quad(r.x0, r.y0 - sw - CURB_W,
                              r.x1, r.y0 - CURB_W, z=0.01)
            all_v.append(v); all_f.append(f + offset); offset += len(v)
            v, f = make_quad(r.x0, r.y1 + CURB_W,
                              r.x1, r.y1 + CURB_W + sw, z=0.01)
            all_v.append(v); all_f.append(f + offset); offset += len(v)

    return np.vstack(all_v), np.vstack(all_f)


def _make_cylinder(x, y, z, radius, height, n=8):
    """Cylinder mesh: returns (verts, faces) lists."""
    angles = np.linspace(0, 2 * np.pi, n, endpoint=False)
    ca, sa = np.cos(angles), np.sin(angles)
    verts, faces = [], []
    # Bottom ring
    for i in range(n):
        verts.append([x + radius * ca[i], y + radius * sa[i], z])
    # Top ring
    for i in range(n):
        verts.append([x + radius * ca[i], y + radius * sa[i], z + height])
    # Side faces
    for i in range(n):
        j = (i + 1) % n
        faces.append([i, j, n + j])
        faces.append([i, n + j, n + i])
    # Bottom cap
    for i in range(1, n - 1):
        faces.append([0, i + 1, i])
    # Top cap
    for i in range(1, n - 1):
        faces.append([n, n + i, n + i + 1])
    return verts, faces


def _make_cone(x, y, z, radius, height, n=8):
    """Cone mesh: returns (verts, faces) lists."""
    angles = np.linspace(0, 2 * np.pi, n, endpoint=False)
    ca, sa = np.cos(angles), np.sin(angles)
    verts, faces = [], []
    # Base ring
    for i in range(n):
        verts.append([x + radius * ca[i], y + radius * sa[i], z])
    # Tip
    tip = n
    verts.append([x, y, z + height])
    # Side faces
    for i in range(n):
        j = (i + 1) % n
        faces.append([i, j, tip])
    # Base cap
    for i in range(1, n - 1):
        faces.append([0, i + 1, i])
    return verts, faces


def _make_sphere_crown(x, y, z, radius, n_lat=4, n_lon=8):
    """Half-sphere crown (dome): returns (verts, faces) lists."""
    verts, faces = [], []
    # Top pole
    verts.append([x, y, z + radius])
    # Latitude rings (from top down to equator)
    for i in range(1, n_lat + 1):
        phi = (np.pi / 2) * i / n_lat  # 0 to pi/2
        r = radius * np.sin(phi)
        zz = z + radius * np.cos(phi)
        for j in range(n_lon):
            theta = 2 * np.pi * j / n_lon
            verts.append([x + r * np.cos(theta), y + r * np.sin(theta), zz])
    # Top cap (connect pole to first ring)
    for j in range(n_lon):
        j2 = (j + 1) % n_lon
        faces.append([0, 1 + j2, 1 + j])
    # Middle rings
    for i in range(n_lat - 1):
        ring1 = 1 + i * n_lon
        ring2 = 1 + (i + 1) * n_lon
        for j in range(n_lon):
            j2 = (j + 1) % n_lon
            faces.append([ring1 + j, ring1 + j2, ring2 + j2])
            faces.append([ring1 + j, ring2 + j2, ring2 + j])
    # Bottom cap
    last_ring = 1 + (n_lat - 1) * n_lon
    bottom = len(verts)
    verts.append([x, y, z])
    for j in range(n_lon):
        j2 = (j + 1) % n_lon
        faces.append([last_ring + j, last_ring + j2, bottom])
    return verts, faces


def make_tree(x, y, z=0.0, seed_val=0):
    """Generate a procedural tree with varied shapes.

    3 tree types:
      0 = Round deciduous (sphere crown)
      1 = Conical pine (2-3 stacked cones)
      2 = Multi-layer deciduous (2 sphere layers)
    """
    rng = np.random.default_rng(seed_val)
    tree_type = seed_val % 3
    n = TREE_SIDES

    # Random variation
    scale = rng.uniform(0.7, 1.3)
    trunk_h = TREE_TRUNK_H * scale * rng.uniform(0.8, 1.2)
    trunk_r = TREE_TRUNK_R * rng.uniform(0.7, 1.1)

    all_verts = []
    all_faces = []

    # Trunk
    tv, tf = _make_cylinder(x, y, z, trunk_r, trunk_h, n)
    all_verts.extend(tv)
    all_faces.extend(tf)
    offset = len(tv)

    crown_base = z + trunk_h * 0.85  # crown overlaps trunk slightly

    if tree_type == 0:
        # Round deciduous — sphere dome
        crown_r = TREE_CROWN_R * scale * rng.uniform(0.8, 1.2)
        cv, cf = _make_sphere_crown(x, y, crown_base, crown_r, n_lat=3, n_lon=n)
        cf = [[f[0] + offset, f[1] + offset, f[2] + offset] for f in cf]
        all_verts.extend(cv)
        all_faces.extend(cf)

    elif tree_type == 1:
        # Conical pine — 2-3 stacked cones getting smaller
        n_layers = rng.choice([2, 3])
        for layer in range(n_layers):
            frac = layer / n_layers
            cone_r = TREE_CROWN_R * scale * (1.0 - frac * 0.35) * rng.uniform(0.85, 1.15)
            cone_h = TREE_CROWN_H * scale * 0.6 * rng.uniform(0.85, 1.15)
            cone_z = crown_base + layer * cone_h * 0.55
            cv, cf = _make_cone(x, y, cone_z, cone_r, cone_h, n)
            cf = [[f[0] + offset, f[1] + offset, f[2] + offset] for f in cf]
            all_verts.extend(cv)
            all_faces.extend(cf)
            offset += len(cv)

    else:
        # Multi-layer deciduous — 2 overlapping domes
        for layer in range(2):
            off_x = rng.uniform(-0.5, 0.5) * scale
            off_y = rng.uniform(-0.5, 0.5) * scale
            crown_r = TREE_CROWN_R * scale * rng.uniform(0.7, 1.1)
            layer_z = crown_base + layer * crown_r * 0.4
            cv, cf = _make_sphere_crown(
                x + off_x, y + off_y, layer_z, crown_r, n_lat=3, n_lon=n)
            cf = [[f[0] + offset, f[1] + offset, f[2] + offset] for f in cf]
            all_verts.extend(cv)
            all_faces.extend(cf)
            offset += len(cv)

    return (np.array(all_verts, dtype=np.float32),
            np.array(all_faces, dtype=np.int32))


def generate_trees(roads, building_footprints, town_w, town_h, seed=42):
    """Place trees along sidewalks, avoiding building footprints."""
    rng = np.random.default_rng(seed + 100)
    all_v, all_f = [], []
    offset = 0
    tree_id = 0

    # Collect tree candidate positions along roads
    positions = []

    for r in roads:
        sw = SIDEWALK_W
        if (r.y1 - r.y0) > (r.x1 - r.x0):
            # N-S road — trees along sidewalks
            ys = np.arange(r.y0 + 5, r.y1 - 5, TREE_SPACING)
            for y in ys:
                # Left sidewalk
                positions.append((r.x0 - CURB_W - sw / 2, y))
                # Right sidewalk
                positions.append((r.x1 + CURB_W + sw / 2, y))
        else:
            # E-W road
            xs = np.arange(r.x0 + 5, r.x1 - 5, TREE_SPACING)
            for x in xs:
                positions.append((x, r.y0 - CURB_W - sw / 2))
                positions.append((x, r.y1 + CURB_W + sw / 2))

    # Filter out trees that overlap building footprints
    fps = np.array(building_footprints) if building_footprints else np.zeros((0, 4))

    for px, py in positions:
        # Check overlap with any building footprint (with margin)
        if len(fps) > 0:
            inside = ((px > fps[:, 0] - 2) & (px < fps[:, 2] + 2) &
                      (py > fps[:, 1] - 2) & (py < fps[:, 3] + 2))
            if inside.any():
                continue

        # Bounds check
        if px < 2 or px > town_w - 2 or py < 2 or py > town_h - 2:
            continue

        v, f = make_tree(px, py, seed_val=tree_id * 7 + seed)
        all_v.append(v)
        all_f.append(f + offset)
        offset += len(v)
        tree_id += 1

    if not all_v:
        return np.zeros((0, 3), np.float32), np.zeros((0, 3), np.int32)
    return np.vstack(all_v), np.vstack(all_f)


# ---------------------------------------------------------------------------
# Road markings — crosswalks + center lines
# ---------------------------------------------------------------------------
def generate_crosswalks(roads):
    """Generate zebra crossing markings at intersections."""
    all_v, all_f = [], []
    offset = 0
    z = 0.04  # above road surface

    # Separate NS and EW roads
    ns_roads = [r for r in roads if (r.y1 - r.y0) > (r.x1 - r.x0)]
    ew_roads = [r for r in roads if (r.x1 - r.x0) >= (r.y1 - r.y0)]

    # At each intersection, place crosswalks
    for ns in ns_roads:
        for ew in ew_roads:
            # Check if they overlap
            if ns.x1 < ew.x0 or ns.x0 > ew.x1:
                continue
            if ew.y1 < ns.y0 or ew.y0 > ns.y1:
                continue

            # Intersection center
            ix = (max(ns.x0, ew.x0) + min(ns.x1, ew.x1)) / 2
            iy = (max(ns.y0, ew.y0) + min(ns.y1, ew.y1)) / 2

            # Crosswalk across NS road (E-W stripes)
            stripe_w = 0.5
            stripe_gap = 0.5
            stripe_len = ns.x1 - ns.x0 - 1.0  # slightly narrower than road
            n_stripes = int(min(ns.width, ew.width) / (stripe_w + stripe_gap))

            # North crosswalk
            cy = ew.y0 - 0.5  # just before intersection
            for s in range(n_stripes):
                sx = ns.x0 + 0.5
                sy = cy - n_stripes * (stripe_w + stripe_gap) / 2 + s * (stripe_w + stripe_gap)
                v, f = make_quad(sx, sy, sx + stripe_len, sy + stripe_w, z)
                all_v.append(v); all_f.append(f + offset); offset += len(v)

            # South crosswalk
            cy = ew.y1 + 0.5
            for s in range(n_stripes):
                sx = ns.x0 + 0.5
                sy = cy + s * (stripe_w + stripe_gap)
                v, f = make_quad(sx, sy, sx + stripe_len, sy + stripe_w, z)
                all_v.append(v); all_f.append(f + offset); offset += len(v)

            # East crosswalk (N-S stripes across EW road)
            cx = ns.x1 + 0.5
            for s in range(n_stripes):
                sy = ew.y0 + 0.5
                sx = cx + s * (stripe_w + stripe_gap)
                v, f = make_quad(sx, sy, sx + stripe_w, sy + ew.width - 1.0, z)
                all_v.append(v); all_f.append(f + offset); offset += len(v)

            # West crosswalk
            cx = ns.x0 - n_stripes * (stripe_w + stripe_gap) - 0.5
            for s in range(n_stripes):
                sy = ew.y0 + 0.5
                sx = cx + s * (stripe_w + stripe_gap)
                v, f = make_quad(sx, sy, sx + stripe_w, sy + ew.width - 1.0, z)
                all_v.append(v); all_f.append(f + offset); offset += len(v)

    if not all_v:
        return np.zeros((0, 3), np.float32), np.zeros((0, 3), np.int32)
    return np.vstack(all_v), np.vstack(all_f)


def generate_center_lines(roads):
    """Generate dashed center line markings on roads."""
    all_v, all_f = [], []
    offset = 0
    z = 0.04
    dash_len = 3.0
    dash_gap = 3.0
    line_w = 0.15

    for r in roads:
        if (r.y1 - r.y0) > (r.x1 - r.x0):
            # NS road — center line along Y
            cx = (r.x0 + r.x1) / 2 - line_w / 2
            y = r.y0 + 2.0
            while y + dash_len < r.y1 - 2.0:
                v, f = make_quad(cx, y, cx + line_w, y + dash_len, z)
                all_v.append(v); all_f.append(f + offset); offset += len(v)
                y += dash_len + dash_gap
        else:
            # EW road — center line along X
            cy = (r.y0 + r.y1) / 2 - line_w / 2
            x = r.x0 + 2.0
            while x + dash_len < r.x1 - 2.0:
                v, f = make_quad(x, cy, x + dash_len, cy + line_w, z)
                all_v.append(v); all_f.append(f + offset); offset += len(v)
                x += dash_len + dash_gap

    if not all_v:
        return np.zeros((0, 3), np.float32), np.zeros((0, 3), np.int32)
    return np.vstack(all_v), np.vstack(all_f)


# ---------------------------------------------------------------------------
# Ground plane
# ---------------------------------------------------------------------------
def generate_ground(town_w, town_h, margin=50.0):
    """Big flat ground plane under everything."""
    v, f = make_quad(-margin, -margin, town_w + margin, town_h + margin,
                      z=-0.01)
    return v, f


# ---------------------------------------------------------------------------
# OBJ export
# ---------------------------------------------------------------------------
def save_obj(path, verts, faces, name="mesh"):
    """Save vertices + faces as OBJ."""
    with open(path, 'w') as f:
        f.write(f"# {name}\n")
        f.write(f"# {len(verts)} vertices, {len(faces)} faces\n")
        for v in verts:
            f.write(f"v {v[0]:.4f} {v[1]:.4f} {v[2]:.4f}\n")
        for face in faces:
            # OBJ faces are 1-indexed
            f.write(f"f {face[0]+1} {face[1]+1} {face[2]+1}\n")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default="./town_export")
    parser.add_argument("--n_buildings", type=int, default=45)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--catalog", default=CATALOG_PATH)
    args = parser.parse_args()

    t0 = time.time()
    print("=" * 60)
    print("Phase 10 — Town Generator")
    print("=" * 60)

    os.makedirs(args.output, exist_ok=True)

    # Load building catalog
    print("\n[1/6] Loading building catalog...")
    catalog = load_catalog(MODELS_DIR, args.catalog)
    print(f"  {len(catalog)} buildings available")

    # Select buildings
    print(f"\n[2/6] Selecting {args.n_buildings} buildings...")
    selected = select_buildings(catalog, args.n_buildings, args.seed)
    total_tris = sum(b.n_faces for b in selected)
    print(f"  Selected {len(selected)} buildings, {total_tris:,} tris")

    # Generate road grid
    print("\n[3/6] Generating road grid...")
    roads, blocks = generate_road_grid(TOWN_W, TOWN_H, args.seed)
    print(f"  {len(roads)} road segments, {len(blocks)} blocks")

    # Place buildings
    print("\n[4/6] Placing buildings...")
    placements = place_buildings(blocks, selected, args.seed)
    footprints = [p.footprint for p in placements]
    print(f"  {len(placements)} buildings placed")

    # Generate infrastructure geometry
    print("\n[5/6] Generating infrastructure...")

    road_v, road_f = generate_road_meshes(roads)
    print(f"  Roads: {len(road_v)} verts, {len(road_f)} faces")

    curb_v, curb_f = generate_curb_meshes(roads)
    print(f"  Curbs: {len(curb_v)} verts, {len(curb_f)} faces")

    sw_v, sw_f = generate_sidewalk_meshes(roads)
    print(f"  Sidewalks: {len(sw_v)} verts, {len(sw_f)} faces")

    tree_v, tree_f = generate_trees(roads, footprints, TOWN_W, TOWN_H,
                                     args.seed)
    n_trees = len(tree_f) // 20 if len(tree_f) > 0 else 0  # rough estimate
    print(f"  Trees: ~{n_trees} trees, {len(tree_v)} verts")

    crosswalk_v, crosswalk_f = generate_crosswalks(roads)
    print(f"  Crosswalks: {len(crosswalk_v)} verts, {len(crosswalk_f)} faces")

    centerline_v, centerline_f = generate_center_lines(roads)
    print(f"  Center lines: {len(centerline_v)} verts, {len(centerline_f)} faces")

    ground_v, ground_f = generate_ground(TOWN_W, TOWN_H)

    # Export
    print("\n[6/6] Exporting...")

    save_obj(os.path.join(args.output, "roads.obj"), road_v, road_f, "roads")
    save_obj(os.path.join(args.output, "curbs.obj"), curb_v, curb_f, "curbs")
    save_obj(os.path.join(args.output, "sidewalks.obj"), sw_v, sw_f,
             "sidewalks")
    save_obj(os.path.join(args.output, "trees.obj"), tree_v, tree_f, "trees")
    save_obj(os.path.join(args.output, "ground.obj"), ground_v, ground_f,
             "ground")
    if len(crosswalk_v) > 0:
        save_obj(os.path.join(args.output, "crosswalks.obj"),
                 crosswalk_v, crosswalk_f, "crosswalks")
    if len(centerline_v) > 0:
        save_obj(os.path.join(args.output, "centerlines.obj"),
                 centerline_v, centerline_f, "centerlines")

    # Scene descriptor
    scene = {
        "town_size": [TOWN_W, TOWN_H],
        "seed": args.seed,
        "buildings": [asdict(p) for p in placements],
        "road_segments": [asdict(r) for r in roads],
        "blocks": blocks,
        "infrastructure": {
            "roads_obj": "roads.obj",
            "curbs_obj": "curbs.obj",
            "sidewalks_obj": "sidewalks.obj",
            "trees_obj": "trees.obj",
            "ground_obj": "ground.obj",
            "crosswalks_obj": "crosswalks.obj",
            "centerlines_obj": "centerlines.obj",
        },
        "stats": {
            "n_buildings": len(placements),
            "n_trees": n_trees,
            "n_road_segments": len(roads),
            "n_blocks": len(blocks),
            "building_tris": total_tris,
        },
    }

    scene_path = os.path.join(args.output, "scene.json")
    with open(scene_path, 'w') as f:
        json.dump(scene, f, indent=2)

    elapsed = time.time() - t0
    print(f"\n{'=' * 60}")
    print(f"Town generated in {elapsed:.2f}s")
    print(f"  Buildings: {len(placements)}")
    print(f"  Trees: {n_trees}")
    print(f"  Roads: {len(roads)} segments")
    print(f"  Output: {args.output}/")
    print(f"  Scene: {scene_path}")
    print(f"{'=' * 60}")


if __name__ == "__main__":
    main()
